add_definitions(-D_USE_MATH_DEFINES)

IF(BUILD_K52_LIBRARY_TYPE STREQUAL Dynamic)
    SET(K52_LIBS_TYPE SHARED)
    SET(K52_LIBS_TYPE_DYNAMIC TRUE)
ELSE()
    #Default if Static
    SET(K52_LIBS_TYPE STATIC)
    SET(K52_LIBS_TYPE_DYNAMIC FALSE)
ENDIF()